"""
Daily Intelligence Brief Generator
Creates a Chairman's Daily Brief note in the Obsidian vault.
Summarizes pipeline activity, new intelligence, and action items.

Runs once daily at 6:00 AM via orchestrator.
"""

import json
import logging
from datetime import datetime, timedelta
from pathlib import Path

from config.settings import (
    VAULT_INTELLIGENCE,
    VAULT_TRANSCRIPTS,
    VAULT_RAW,
    STATUS_FILE,
)

logger = logging.getLogger('content-os.daily-brief')

OBSIDIAN_VAULT = Path(__file__).parent.parent / 'obsidian_vault'


def generate_daily_brief() -> str:
    """Generate the Chairman's Daily Intelligence Brief."""
    today = datetime.now()
    yesterday = today - timedelta(days=1)
    date_str = today.strftime('%Y-%m-%d')
    display_date = today.strftime('%A, %B %d, %Y')

    # ── Gather Intelligence ──

    # Pipeline status
    pipeline_status = 'unknown'
    last_run = {}
    if STATUS_FILE.exists():
        try:
            status = json.loads(STATUS_FILE.read_text())
            pipeline_status = status.get('system', 'unknown')
            last_run = status.get('last_run', {})
        except Exception:
            pass

    # Count new files since yesterday
    new_raw = _count_new_files(VAULT_RAW, yesterday)
    new_transcripts = _count_new_files(VAULT_TRANSCRIPTS, yesterday)
    new_intel = _count_new_files(VAULT_INTELLIGENCE, yesterday)

    # Total counts
    total_raw = _count_files(VAULT_RAW)
    total_transcripts = _count_files(VAULT_TRANSCRIPTS, '*.json')
    total_intel = _count_files(VAULT_INTELLIGENCE, '*.json')

    # Recent quotes
    recent_quotes = _get_recent_quotes(3)

    # Recent predictions
    recent_predictions = _get_recent_predictions(3)

    # ── Build the Brief ──

    brief = f"""# 📋 Chairman's Daily Brief — {display_date}

> Auto-generated by Content OS at {today.strftime('%H:%M')}
> System Status: {'🟢 ONLINE' if pipeline_status in ('online', 'idle') else '🔴 ' + pipeline_status.upper()}

---

## 📊 Pipeline Summary

| Metric | Today | Total |
|--------|-------|-------|
| Raw Assets | +{new_raw} new | {total_raw} total |
| Transcripts | +{new_transcripts} new | {total_transcripts} total |
| Intelligence | +{new_intel} new | {total_intel} total |

### Layer Status
{_format_layer_status(last_run)}

---

## 🔮 Recent Predictions

{_format_predictions(recent_predictions)}

---

## 💎 Recent Quotes

{_format_quotes(recent_quotes)}

---

## ✅ Action Items

1. Review any new transcripts needing analysis
2. Check prediction verification queue
3. Review Content OS module status on ZIION dashboard
4. {"API keys need attention — check Connectors page" if pipeline_status == 'error' else "All systems nominal"}

---

## 🧠 Knowledge Graph Stats

- Total vault notes: {_count_vault_notes()}
- Predictions tracked: {_count_files(OBSIDIAN_VAULT / '01-Predictions', '*.md')}
- Frameworks documented: {_count_files(OBSIDIAN_VAULT / '02-Frameworks', '*.md')}
- Quotes captured: {_count_files(OBSIDIAN_VAULT / '03-Quotes', '*.md')}
- Themes identified: {_count_files(OBSIDIAN_VAULT / '04-Themes', '*.md')}

---

> "The sovereign thinker doesn't start the day reacting. They start with intelligence."

[[Dashboard]] | [[Prediction Tracker]] | [[Quote Bank]] | [[Framework Index]]
"""

    # ── Write to Vault ──
    briefs_dir = OBSIDIAN_VAULT / '09-Daily-Briefs'
    briefs_dir.mkdir(parents=True, exist_ok=True)

    frontmatter = f"""---
tags: [daily-brief, intelligence, auto-generated]
created: {date_str}
type: daily-brief
system_status: {pipeline_status}
---

"""
    note_path = briefs_dir / f'Brief-{date_str}.md'
    note_path.write_text(frontmatter + brief, encoding='utf-8')

    logger.info(f'Daily brief generated: {note_path.name}')
    return str(note_path)


def _count_files(directory: Path, pattern='*') -> int:
    """Count files in a directory."""
    try:
        if not directory.exists():
            return 0
        return len(list(directory.glob(pattern)))
    except Exception:
        return 0


def _count_new_files(directory: Path, since: datetime) -> int:
    """Count files modified since a given datetime."""
    try:
        if not directory.exists():
            return 0
        count = 0
        for f in directory.iterdir():
            if f.is_file() and f.stat().st_mtime > since.timestamp():
                count += 1
        return count
    except Exception:
        return 0


def _count_vault_notes() -> int:
    """Count total notes in the Obsidian vault."""
    try:
        if not OBSIDIAN_VAULT.exists():
            return 0
        return len(list(OBSIDIAN_VAULT.rglob('*.md')))
    except Exception:
        return 0


def _format_layer_status(last_run: dict) -> str:
    """Format layer status for the brief."""
    if not last_run:
        return '_No pipeline runs recorded yet_'
    lines = []
    for layer, timestamp in last_run.items():
        try:
            dt = datetime.fromisoformat(timestamp)
            ago = datetime.now() - dt
            if ago.total_seconds() < 3600:
                time_str = f'{int(ago.total_seconds() / 60)}m ago'
            elif ago.total_seconds() < 86400:
                time_str = f'{int(ago.total_seconds() / 3600)}h ago'
            else:
                time_str = f'{int(ago.total_seconds() / 86400)}d ago'
            lines.append(f'- **{layer}**: Last run {time_str}')
        except Exception:
            lines.append(f'- **{layer}**: {timestamp}')
    return '\n'.join(lines) if lines else '_No data_'


def _get_recent_quotes(count: int) -> list:
    """Get recent quotes from the quote bank."""
    quote_bank = VAULT_INTELLIGENCE / 'quote_bank.json'
    if not quote_bank.exists():
        return []
    try:
        data = json.loads(quote_bank.read_text())
        return data.get('quotes', [])[:count]
    except Exception:
        return []


def _get_recent_predictions(count: int) -> list:
    """Get recent predictions from intelligence outputs."""
    predictions = []
    if not VAULT_INTELLIGENCE.exists():
        return predictions
    for f in sorted(VAULT_INTELLIGENCE.glob('*.json'), reverse=True):
        if f.name in ('quote_bank.json', 'theme_map.json'):
            continue
        try:
            data = json.loads(f.read_text())
            analysis = data.get('analysis', data)
            preds = analysis.get('predictions', [])
            predictions.extend(preds)
        except Exception:
            continue
        if len(predictions) >= count:
            break
    return predictions[:count]


def _format_predictions(predictions: list) -> str:
    """Format predictions for the brief."""
    if not predictions:
        return '_No predictions captured yet. Run the intelligence pipeline to extract predictions from content._'
    lines = []
    for p in predictions:
        claim = p.get('claim', p.get('prediction', 'Unknown'))
        timeline = p.get('timeline', '?')
        lines.append(f'- 🟡 **{claim[:80]}** (Timeline: {timeline})')
    return '\n'.join(lines)


def _format_quotes(quotes: list) -> str:
    """Format quotes for the brief."""
    if not quotes:
        return '_No quotes captured yet. Run the intelligence pipeline to extract quotes from content._'
    lines = []
    for q in quotes:
        text = q.get('text', q.get('quote', ''))
        source = q.get('source', 'Unknown')
        if text:
            lines.append(f'> "{text[:100]}..."\n> — {source}\n')
    return '\n'.join(lines) if lines else '_No quotes available_'


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    path = generate_daily_brief()
    print(f'Brief generated at: {path}')
